#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

hostname=${HOSTNAME:-$(hostname)}

/usr/bin/env figlet "$(hostname)" | /usr/bin/env lolcat -f


